BOX_PAT_RUNC='fill patter 1 lt 1 lc rgb "dark-yellow"'
BOX_PAT_KATA='fill patter 2 lt 1 lc rgb "grey20"'
BOX_PAT_RUNU='fill patter 3 lt 1 lc rgb "midnight-blue"'
BOX_PAT_GVISOR_P='fill patter 4 lt 1 lc rgb "blue"'
BOX_PAT_GVISOR_K='fill patter 5 lt 1 lc rgb "blue"'
BOX_PAT_GRAPH='fill patter 6 lt 1 lc rgb "brown4"'
BOX_PAT_RUNNC='fill patter 7 lt 1 lc rgb "forest-green"'
BOX_PAT_NATIVE='fill patter 0 lt 1 lc rgb "red"'
